/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Abanner: typeof import('./components/abanner/abanner.vue')['default']
    Applist: typeof import('./components/list/applist.vue')['default']
    Aside: typeof import('./components/aside/aside.vue')['default']
    Banner: typeof import('./components/banner/banner.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    IEpPointer: typeof import('~icons/ep/pointer')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IIconPointer: typeof import('~icons/ep/pointer')['default']
    Navbar: typeof import('./components/header/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/SvgIcon.vue')['default']
  }
}
